export enum Role {
  ADMIN = 'A',
  SUPER_ADMIN = 'S',
  BASIC = 'B',
  DEMO = 'D',
}

export enum Entity {
  USER = 'User',
  USERS = 'Users',
  TENANT = 'Tenant',
  TENANTS = 'Tenants',
  COMPANY = 'Company',
  COMPANIES = 'Companies',
  SETTING = 'Setting',
  SETTINGS = 'Settings',
  SITE = 'Site',
  SITES = 'Sites',
  SITE_AREA = 'SiteArea',
  SITE_AREAS = 'SiteAreas',
  TRANSACTION = 'Transaction',
  TRANSACTIONS = 'Transactions',
  CHARGING_STATION = 'ChargingStation',
  CHARGING_STATIONS = 'ChargingStations',
  BILLING = 'Billing',
  LOGGING = 'Logging',
  LOGGINGS = 'Loggings',
  BUILDING = 'Building',
  BUILDINGS = 'Buildings',
  INVOICES = 'INVOICES',
}

export enum Action {
  CREATE = 'Create',
  READ = 'Read',
  UPDATE = 'Update',
  DELETE = 'Delete',
  LOGOUT = 'Logout',
  LIST = 'List',
  RESET = 'Reset',
  CLEAR_CACHE = 'ClearCache',
  REMOTE_START_TRANSACTION = 'RemoteStartTransaction',
  REMOTE_STOP_TRANSACTION = 'RemoteStopTransaction',
  REFUND_TRANSACTION = 'RefundTransaction',
  UNLOCK_CONNECTOR = 'UnlockConnector',
  GET_CONFIGURATION = 'GetConfiguration',
  SYNCHRONIZE_USERS_BILLING = 'SynchronizeUsersBilling',
}
